name: Run 20 Instances (15 min only)

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,
                   11,12,13,14,15,16,17,18,19,20]

    steps:
      - name: Start container
        run: |
          echo "Starting instance ${{ matrix.instance }}"
          docker run -d --name job_${{ matrix.instance }} nduythanh1/selenium-videozz-multiprocess:latest

      - name: Let it run for 15 minutes
        run: sleep 900

      - name: Force stop container
        run: |
          echo "Stopping instance ${{ matrix.instance }}"
          docker rm -f job_${{ matrix.instance }} || true

      - name: Done
        run: echo "Finished instance ${{ matrix.instance }}"
