name: Run 20 Selenium Instances

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        instance: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    steps:
      - name: Pull Docker image
        run: docker pull nduythanh1/selenium-videozz-multiprocess:latest

      - name: Run container (13 minutes)
        run: |
          echo "Starting instance ${{ matrix.instance }}"
          timeout 780s docker run --rm nduythanh1/selenium-videozz-multiprocess:latest || true
          echo "Finished instance ${{ matrix.instance }}"
